export default Object.freeze({
    FETCH_TASKS:         'FETCH_TASKS',
    FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',
    FETCH_TASKS_FAIL:    'FETCH_TASKS_FAIL',

    CREATE_TASK:         'CREATE_TASK',
    CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
    CREATE_TASK_FAIL:    'CREATE_TASK_FAIL',

    DELETE_TASK:         'DELETE_TASK',
    DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
    DELETE_TASK_FAIL:    'DELETE_TASK_FAIL',

    EDIT_TASK:         'EDIT_TASK',
    EDIT_TASK_SUCCESS: 'EDIT_TASK_SUCCESS',
    EDIT_TASK_FAIL:    'EDIT_TASK_FAIL',

    SET_TASK_EDITABLE:   'SET_TASK_EDITABLE',
    SET_TASKS_COMPLETED: 'SET_TASKS_COMPLETED',
    SET_INPUT_CREATE:    'SET_INPUT_CREATE',
    SET_INPUT_EDIT:      'SET_INPUT_EDIT',
});
