export default Object.freeze({
    FETCH_TASKS:         'FETCH_TASKS',
    FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',
    FETCH_TASKS_FAIL:    'FETCH_TASKS_FAIL',

    CREATE_TASK:         'CREATE_TASK',
    CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
    CREATE_TASK_FAIL:    'CREATE_TASK_FAIL',

    DELETE_TASK:         'DELETE_TASK',
    DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
    DELETE_TASK_FAIL:    'DELETE_TASK_FAIL',

    EDIT_TASK:         'EDIT_TASK',
    EDIT_TASK_SUCCESS: 'EDIT_TASK_SUCCESS',
    EDIT_TASK_FAIL:    'EDIT_TASK_FAIL',

    // COMPLETE_TASK:           'COMPLETE_TASK',
    // COMPLETE_TASK_SUCCESS:   'COMPLETE_TASK_SUCCESS',
    // COMPLETE_TASK_FAIL:      'COMPLETE_TASK_FAIL',

    // FAVORITE_TASK:         'FAVORITE_TASK',
    // FAVORITE_TASK_SUCCESS: 'FAVORITE_TASK_SUCCESS',
    // FAVORITE_TASK_FAIL:    'FAVORITE_TASK_FAIL',
});